name: xtyle
description: Xtyle provides mutiligual-styled Text and TextEditingController. You can use different fontFamily for each languages.
version: 0.1.3
homepage: https://github.com/TykanN/xtyle

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: