name: xtyle
description: Xtyle provides mutiligual-styled Text and TextEditingController. You can use different fontFamily for each languages.
version: 0.2.0
homepage: https://github.com/TykanN/xtyle

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
